server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: docker-wsl-logs
  static_configs:
  - targets: [localhost]
    labels:
      job: docker-logs
      __path__: /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/**/logs/*.log
  pipeline_stages:
  - json:
      expressions:
        log: log
        stream: stream
        time: time
  - timestamp:
      source: time
      format: RFC3339Nano
  - labels:
      stream:
  - output:
      source: log