# Generated by Django 5.1.7 on 2025-04-12 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_control_api', '0001_initial'),
        ('seller_store_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_store', to='seller_store_api.store'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product_control_api.product'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_control_api.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_categories', to='product_control_api.subcategory'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='options',
            field=models.ManyToManyField(related_name='product_variants', to='product_control_api.variantoption'),
        ),
        migrations.AddField(
            model_name='variantoption',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_control_api.varianttype'),
        ),
    ]
