# Generated by Django 5.1.7 on 2025-04-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_control_api', '0003_alter_productvariant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='quantity',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
