# Generated by Django 5.1.7 on 2025-04-12 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_control_api', '0005_alter_product_description_and_more'),
        ('usercontrol_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, through='usercontrol_api.WishlistItem', to='product_control_api.productvariant'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_control_api.productvariant'),
        ),
    ]
