# Generated by Django 5.1.7 on 2025-04-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol_api', '0004_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
