# Generated by Django 5.1.7 on 2025-04-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol_api', '0005_alter_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('delivery', 'Delivery'), ('coupon', 'Coupon'), ('other', 'Other')], default='delivery', max_length=8),
        ),
    ]
