# Generated by Django 5.1.7 on 2025-04-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol_api', '0005_alter_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
