# Generated by Django 5.1.7 on 2025-03-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_store_api', '0007_alter_product_price'),
        ('usercontrol_api', '0005_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='seller_store_api.product'),
        ),
    ]
