# Generated by Django 5.1.7 on 2025-04-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol_api', '0006_alter_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(choices=[('purchase', 'покупка'), ('delivery', 'доставка'), ('coupon', 'купон'), ('other', 'другое')], default='delivery', max_length=8),
        ),
    ]
