# Generated by Django 5.1.7 on 2025-04-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol_api', '0009_alter_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, choices=[('purchase', 'покупка'), ('delivery', 'доставка'), ('coupon', 'купон'), ('other', 'другое')], default='other', max_length=8),
        ),
    ]
