# Generated by Django 5.1.7 on 2025-04-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol_api', '0011_alter_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, default='Empty notification', max_length=1000),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, choices=[('purchase', 'покупка'), ('delivery', 'доставка'), ('coupon', 'купон'), ('celler', 'продавец'), ('other', 'другое')], default='other', max_length=50),
        ),
    ]
