# Generated by Django 5.1.7 on 2025-04-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(blank=True, default=1)),
                ('status', models.CharField(choices=[('on the way', 'в пути'), ('delivered', 'доставлено'), ('denied', 'отказано')], default='on the way', max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(blank=True, default=1)),
                ('status', models.CharField(choices=[('on the way', 'в пути'), ('delivered', 'доставлено'), ('denied', 'отказано')], default='delivered', max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
