# Generated by Django 5.1.7 on 2025-04-12 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_system_api', '0001_initial'),
        ('product_control_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_control_api.product'),
        ),
    ]
