# Generated by Django 5.1.7 on 2025-05-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system_api', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(default=999, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paybox_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='KZT', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
