# Generated by Django 5.1.7 on 2025-04-12 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system_api', '0003_initial'),
        ('product_control_api', '0005_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_control_api.productvariant'),
        ),
        migrations.AlterField(
            model_name='history',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_control_api.productvariant'),
        ),
    ]
