# Generated by Django 5.1.7 on 2025-04-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system_api', '0004_alter_delivery_product_alter_history_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled')], default='pending', max_length=10)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
