# Generated by Django 5.2.4 on 2025-08-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_store_api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='star_rating_valid',
        ),
    ]
