# Generated by Django 5.1.7 on 2025-04-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_store_api', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
