# Generated by Django 5.1.7 on 2025-03-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_store_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
