# Generated by Django 5.1.7 on 2025-04-13 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_control_api', '0005_alter_product_description_and_more'),
        ('seller_store_api', '0003_alter_review_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('stars__gte', 1), ('stars__lte', 5)), name='star_raiting_valid', violation_error_message='Можно ставить только от 1 до 5 звезд.'),
        ),
    ]
