# Generated by Django 5.1.7 on 2025-04-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_store_api', '0004_review_star_raiting_valid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='photo',
            new_name='image',
        ),
    ]
