# Generated by Django 5.1.7 on 2025-03-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_store_api', '0005_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='Продавец не оставил описание об товаре.', max_length=1000, null=True),
        ),
    ]
