# Generated by Django 5.1.7 on 2025-04-27 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_control_api', '0006_productvariant_views'),
        ('seller_store_api', '0005_rename_photo_review_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='star_raiting_valid',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('stars__gte', 1), ('stars__lte', 5)), name='star_rating_valid', violation_error_message='Можно ставить только от 1 до 5 звезд.'),
        ),
    ]
