# Generated by Django 5.1.7 on 2025-03-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_store_api', '0006_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
